# .pre-commit-config.yaml

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.29
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: ruff-check
        name: "Run Ruff Linter via uv"
        entry: uvx ruff check
        language: system
        files: \.py$
      - id: isort-check
        name: "Run isort via uv (check mode)"
        entry: uvx isort --check-only
        language: system
        files: \.py$
