name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
      env:
        UV_PYTHON: "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Sync project environment
        run: uv sync
      - name: Run Ruff Linter
        run: uv run ruff check .
